# Welcome to Bridgetown!
#
# This config file is for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec bridgetown serve'. If you change this file, please restart the
# server process.
#
# For reloadable site metadata like title, SEO description, social media
# handles, etc., take a look at src/_data/site_metadata.yml
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

url: "https://www.demainilpleut.dev" # the base hostname & protocol for your site, e.g. https://example.com

permalink: pretty

#Â Change default build output directory to "public"
destination: public

# Disable native syntax highlighting
highlighter: none

# Other options you might want to investigate:
#
# base_path: "/" # the subpath of your site, e.g. /blog
timezone: Europe/Paris
pagination:
  enabled: true
